global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - prometheus.rules.yml

scrape_configs:
  - job_name: "my-monitored-app"
    dns_sd_configs:
      - names:
          - "tasks.my-monitored-app"
          - "my-monitored-app-snapshot-enabled"
        type: "A"
        port: 8080
    metrics_path: "/actuator/prometheus"
